# Generated by Django 5.2.6 on 2025-09-06 02:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('authority', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Approved', 'Approved')], default='Pending', max_length=50)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='gov_filings/')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='A unique ID for each student (e.g., CPB00002).', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('has_birth_certificate', models.BooleanField(default=False)),
                ('has_sponsorship_contract', models.BooleanField(default=False)),
                ('current_grade', models.CharField(max_length=50)),
                ('eep_enroll_date', models.DateField()),
                ('out_of_program_date', models.DateField(blank=True, null=True)),
                ('student_status', models.CharField(choices=[('Pending Qualification', 'Pending Qualification'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending Qualification', max_length=50)),
                ('sponsorship_status', models.CharField(choices=[('Sponsored', 'Sponsored'), ('Unsponsored', 'Unsponsored')], default='Unsponsored', max_length=50)),
                ('has_housing_sponsorship', models.BooleanField(default=False)),
                ('sponsor_name', models.CharField(blank=True, max_length=255)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_contact_info', models.TextField(blank=True)),
                ('home_location', models.CharField(max_length=255)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_follow_up', models.DateField()),
                ('location_of_follow_up', models.CharField(max_length=255)),
                ('health_status_notes', models.TextField()),
                ('risk_factors', models.TextField(help_text='A text field for a checklist of specific risk factors.')),
                ('parent_work_status', models.CharField(blank=True, max_length=255)),
                ('hygiene_products_provided', models.BooleanField(default=False)),
                ('staff_notes', models.TextField(blank=True, help_text='Staff notes, recommendations, and protection concerns.')),
                ('completed_by', models.CharField(max_length=100)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_records', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_period', models.CharField(help_text='The period the report covers (e.g., "Q1 2025").', max_length=100)),
                ('grade_level', models.CharField(max_length=50)),
                ('subjects_and_grades', models.TextField()),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pass_fail_status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('teacher_comments', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_reports', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('School Fees', 'School Fees'), ('Hot Lunches', 'Hot Lunches'), ('Gas', 'Gas'), ('Sponsorship', 'Sponsorship'), ('Donation', 'Donation'), ('Other', 'Other')], max_length=50)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student')),
            ],
        ),
    ]
