# Generated by Django 5.2.6 on 2025-09-08 06:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dueDate',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='followuprecord',
            name='child_current_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='followuprecord',
            name='child_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='academicreport',
            name='overall_average',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_details',
            field=models.JSONField(default=core.models.default_parent_details),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_details',
            field=models.JSONField(default=core.models.default_parent_details),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_schooling_details',
            field=models.JSONField(default=core.models.default_schooling_details),
        ),
    ]
