# Generated by Django 5.2.6 on 2025-09-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sponsorship_start_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='sponsor_name',
        ),
        migrations.AddField(
            model_name='student',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_students', to='core.sponsor'),
        ),
    ]
