# Generated by Django 5.2.6 on 2025-09-12 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_sponsor_remove_student_sponsor_name_student_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=dict)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roleprofile', to='auth.group')),
            ],
        ),
    ]
