# Generated by Django 5.2.6 on 2025-09-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_roleprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuprecord',
            name='child_current_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='followuprecord',
            name='child_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
