# Generated by Django 5.2.6 on 2025-09-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_followuprecord_child_current_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followuprecord',
            name='child_current_age',
        ),
        migrations.RemoveField(
            model_name='followuprecord',
            name='child_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='household_members_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='siblings_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
