# Generated by Django 5.2.6 on 2025-09-30 09:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_studentdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='has_sponsorship_contract',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sponsor',
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('has_sponsorship_contract', models.BooleanField(default=False)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'sponsor')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsored_students', through='core.Sponsorship', to='core.sponsor'),
        ),
    ]
